### PR TITLE
Updates CLI and adds logging

### PR DESCRIPTION
**Pull request by moonso**
Hi,

I've made a small PR with an updated CLI that uses [click](http://click.pocoo.org/5/).
Also added colored logs and replaced prints with loggin.

Please check if you like it 😄

### CODE REVIEW

**Comment by brentp** [comment]
this looks great! any changes you want to add or is this ready? 

we could make `coloredlogs` optional with a `try/except ImportError` but that's not necessary.

**Comment by moonso** [comment]
No I think this is ok for now. 
I've added `coloredlogs` to `requirements.txt` so it should be fine when upgrading?

**Comment by moonso** [comment]
Btw thanks for an excellent tool, we will probably be able to replace several tools like plink and homemade stuff with this!

**Comment by brentp** [comment]
yes, the install will be ok. it would just remove 1 required dependency for conda.

**Comment by brentp** [comment]
glad to hear it's useful!

**Comment by moonso** [comment]
Ok then, feel free to merge whenever you are ready or tell me if there is anything else I should add

**Pull request merged**
